name: ABot API Test Execution

on:
  workflow_dispatch:
    inputs:
      feature_tag:
        description: 'Feature tag to execute (e.g. sanity, regression)'
        required: false
        default: 'sanity'

jobs:
  run-abot-tests:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman & Reporter
      run: npm install -g newman newman-reporter-htmlextra

    - name: Create Reports Folder
      run: mkdir -p postman/newman/reports

    - name: Inject featureTag using sed
      run: |
       sed -i 's/"featureTags": *"[^"]*"/"featureTags": "${{ github.event.inputs.feature_tag }}"/' postman/ABot_Environment.json


    - name: Run ABot Postman Collection with CLI Logging
      id: abot_test
      continue-on-error: true
      run: |
        newman run "postman/ABot_API_TechM.postman_collection.json" \
          --environment "postman/ABot_Environment.json" \
          --reporters cli,json,htmlextra \
          --reporter-json-export "postman/newman/reports/results.json" \
          --reporter-htmlextra-export "postman/newman/reports/results.html" \
          --verbose | tee postman/newman/reports/cli-log.txt

    - name: Upload HTML Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: abot-api-results-html
        path: postman/newman/reports/results.html

    - name: Upload CLI Log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: abot-cli-log
        path: postman/newman/reports/cli-log.txt

    - name: Generate ABot Test Summary HTML
      if: always()
      run: |
        node -e '
        const fs = require("fs");
        if (!fs.existsSync("postman/newman/reports/results.json")) {
          console.error("❌ No result file found");
          process.exit(1);
        }
        const data = JSON.parse(fs.readFileSync("postman/newman/reports/results.json", "utf-8"));
        const exec = data.run.executions.find(e => e.item.name.includes("Execution Summary"));
        if (!exec || !exec.response) {
          console.error("❌ Execution Summary not found in response");
          process.exit(1);
        }
        const body = Buffer.from(exec.response.stream.data).toString("utf-8");
        const summary = JSON.parse(body);
        const total = summary?.feature_summary?.result?.totalScenarios || 0;
        const passed = summary?.feature_summary?.result?.totalScenariosPassed?.totalScenariosPassedNumber || 0;
        const failed = summary?.feature_summary?.result?.totalScenariosFailed?.totalScenariosFailedNumber || 0;
        const html = `<!DOCTYPE html><html><body>
          <h2>ABot Test Summary</h2>
          <p><strong>Total:</strong> ${total}</p>
          <p><strong>Passed:</strong> ${passed}</p>
          <p><strong>Failed:</strong> ${failed}</p>
          </body></html>`;
        fs.writeFileSync("postman/newman/reports/abot-summary.html", html);
        '

    - name: Upload ABot Test Summary HTML
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: abot-summary
        path: postman/newman/reports/abot-summary.html

    - name: Fail if ABot Test Fails
      run: |
        node -e '
        const fs = require("fs");
        const data = JSON.parse(fs.readFileSync("postman/newman/reports/results.json", "utf-8"));
        const exec = data.run.executions.find(e => e.item.name.includes("Execution Summary"));
        const body = Buffer.from(exec.response.stream.data).toString("utf-8");
        const summary = JSON.parse(body);
        const failed = summary?.feature_summary?.result?.totalScenarios?.totalScenariosFailed?.totalScenariosFailedNumber || 0;
        if (failed > 0) {
          console.error(`❌ ABot test failed: ${failed} scenario(s) failed`);
          process.exit(1);
        } else {
          console.log("✅ All ABot feature files passed.");
        }
        '
