name: ABot API Test Execution

on:
  workflow_dispatch:

jobs:
  run-abot-tests:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman & Reporter
      run: npm install -g newman newman-reporter-htmlextra

    - name: Create Reports Folder
      run: mkdir -p postman/newman/reports

    - name: Run ABot Postman Collection
      id: abot_test
      continue-on-error: true
      run: |
        newman run postman/ABot_API_postman_collection_updated_with_test.json \
          --environment postman/ABot_Environment.json \
          --reporters cli,json,htmlextra \
          --reporter-json-export postman/newman/reports/results.json \
          --reporter-htmlextra-export postman/newman/reports/results.html \
          --verbose

    - name: Convert JSON to CSV
      run: |
        node -e "
        const fs = require('fs');
        const json = JSON.parse(fs.readFileSync('postman/newman/reports/results.json'));
        const statusExplain = {
          200: 'OK', 201: 'Created', 204: 'No Content',
          400: 'Bad Request', 401: 'Unauthorized',
          403: 'Forbidden', 404: 'Not Found',
          409: 'Conflict', 500: 'Internal Server Error'
        };
        const csv = ['iteration,item_name,method,url,response_code,status,response_time_ms,explanation'];
        json.run.executions.forEach(e => {
          const row = [
            e.cursor?.iteration || 0,
            (e.item?.name || '').replace(/,/g, ' '),
            e.request?.method || '',
            e.request?.url?.raw || '',
            e.response?.code || '',
            e.response?.status || '',
            e.response?.responseTime || '',
            statusExplain[e.response?.code] || 'Unknown'
          ];
          csv.push(row.join(','));
        });
        fs.writeFileSync('postman/newman/reports/results.csv', csv.join('\n'));
        "

    - name: Upload CSV Report
      uses: actions/upload-artifact@v4
      with:
        name: abot-api-results-csv
        path: postman/newman/reports/results.csv

    - name: Upload HTML Report
      uses: actions/upload-artifact@v4
      with:
        name: abot-api-results-html
        path: postman/newman/reports/results.html

    - name: Generate ABot Test Summary HTML
      run: |
        node -e "
        const fs = require('fs');
        const resultPath = 'postman/newman/reports/results.json';
        const outputPath = 'postman/newman/reports/abot-summary.html';
        const data = JSON.parse(fs.readFileSync(resultPath, 'utf-8'));
        const exec = data.run.executions.find(e => e.item.name.includes('Execution summary'));
        const body = Buffer.from(exec.response.stream.data).toString('utf-8');
        const res = JSON.parse(body);
        const total = res?.feature_summary?.result?.totalScenarios?.totalScenarios || 0;
        const passed = res?.feature_summary?.result?.totalScenarios?.totalScenariosPassed?.totalScenariosPassedNumber || 0;
        const failed = res?.feature_summary?.result?.totalScenarios?.totalScenariosFailed?.totalScenariosFailedNumber || 0;
        const html = `<!DOCTYPE html><html><body>
<h2>ABot Test Summary</h2>
<p><strong>Total Scenarios:</strong> ${total}</p>
<p><strong>Passed:</strong> ${passed}</p>
<p><strong>Failed:</strong> ${failed}</p>
</body></html>`;
        fs.writeFileSync(outputPath, html);
        "

    - name: Upload ABot Test Summary HTML
      uses: actions/upload-artifact@v4
      with:
        name: abot-summary
        path: postman/newman/reports/abot-summary.html

    - name: Fail if ABot Test Fails
      run: |
        node -e "
        const fs = require('fs');
        const data = JSON.parse(fs.readFileSync('postman/newman/reports/results.json', 'utf-8'));
        const execSummary = data.run.executions.find(e => e.item.name.includes('Execution summary'));
        const body = Buffer.from(execSummary.response.stream.data).toString('utf-8');
        const summary = JSON.parse(body);
        const failed = summary?.feature_summary?.result?.totalScenarios?.totalScenariosFailed?.totalScenariosFailedNumber || 0;
        if (failed > 0) {
          console.error(`❌ ABot test failed: ${failed} scenario(s) failed`);
          process.exit(1);
        } else {
          console.log('✅ All ABot feature files passed.');
        }
        "
